# Generated by Django 6.0.4 on 2026-04-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
