# Generated by Django 6.0.4 on 2026-04-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0002_alter_corte_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='precio',
            field=models.IntegerField(max_length=10),
        ),
    ]
