# Generated by Django 6.0.4 on 2026-04-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0003_alter_corte_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
