# Generated by Django 6.0.4 on 2026-04-15 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0004_alter_corte_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corte.corte')),
            ],
        ),
    ]
