# Generated by Django 6.0.4 on 2026-04-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0005_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='corte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
