# Generated by Django 4.2.11 on 2026-06-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0006_reserva_is_active_alter_corte_id_alter_reserva_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='is_active',
        ),
        migrations.AddField(
            model_name='corte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cortes/'),
        ),
    ]
